apiVersion: v1
kind: Service
metadata:
  name: bravo-service
#  namespace: default
  labels:
    app: bravo-service
    version: 0.0.1-SNAPSHOT
    tier: microservices
spec:
  type: NodePort
  selector:
    app: bravo-service
    version: 0.0.1-SNAPSHOT
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 30721
    protocol: TCP
